---

- name: create groups
  group:
    name: '{{ item.groupname }}'
    gid: '{{ item.gid }}'
  with_items: '{{ users_groups_available | default([]) }}'

- name: create groups for users
  group:
    name: '{{ item.username }}'
    gid: '{{ item.uid }}'
  with_items: '{{ users_available | default([]) }}'

- name: create users
  user:
    name: '{{ item.username }}'
    group: '{{ item.username }}'
    groups: '{{ item.groups|join(",") }}'
    shell: '{{ item.shell }}'
    comment: '{{ item.name }}'
    uid: '{{ item.uid if item.uid }}'
    createhome: '{{ item.createhomedir }}'
    password: '{{ item.password }}'
    update_password: '{{ item.update_password }}'
  with_items: '{{ users_available | default([]) }}'

- name: set authorized_keys for users
  authorized_key:
    user: '{{ item.username }}'
    key: '{{ lookup("file", "../files/" + item.username + ".pub") }}'
  with_items: '{{ users_available | default([]) }}'
  when: item.createhomedir and item.upload_key

- name: remove users
  user:
    name: '{{ item }}'
    state: absent
    remove: yes
  with_items: '{{ users_deleted | default([]) }}'

- name: remove groups for users
  group:
    name: '{{ item }}'
    state: absent
  with_items: '{{ users_deleted | default([]) }}'

- name: remove groups
  group:
    name: '{{ item }}'
    state: absent
  with_items: '{{ users_groups_deleted | default([]) }}'
